name: PSY427_627
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=py310hca03da5_0
  - aiosignal=1.4.0=py310hca03da5_0
  - alabaster=0.7.16=py310hca03da5_0
  - applaunchservices=0.3.0=py310hca03da5_0
  - appnope=0.1.2=py310hca03da5_1001
  - arrow=1.2.3=py310hca03da5_1
  - astroid=3.3.11=py310hca03da5_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=5.0.1=py310hca03da5_0
  - atomicwrites=1.4.0=py_0
  - attrs=25.4.0=py310hca03da5_2
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.11.0=py310hca03da5_0
  - beautifulsoup4=4.12.3=py310hca03da5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.4.2=py310hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py310h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h73c2a22_1
  - chardet=4.0.0=py310hca03da5_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py310hca03da5_0
  - cloudpickle=3.0.0=py310hca03da5_0
  - colorama=0.4.6=py310hca03da5_0
  - comm=0.2.1=py310hca03da5_0
  - contourpy=1.2.0=py310h48ca7d4_0
  - cookiecutter=2.6.0=py310hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py310h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.8=py310hca03da5_0
  - docstring-to-markdown=0.11=py310hca03da5_0
  - docutils=0.18.1=py310hca03da5_3
  - exceptiongroup=1.2.0=py310hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.51.0=py310h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=hbdbcc25_2
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h5py=3.11.0=py310haafd478_0
  - hdf5=1.12.1=h05c076b_3
  - icu=73.1=h313beb8_0
  - idna=3.7=py310hca03da5_0
  - imagesize=1.4.1=py310hca03da5_0
  - importlib-metadata=7.0.1=py310hca03da5_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - inflection=0.5.1=py310hca03da5_0
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipython=8.25.0=py310hca03da5_0
  - isort=5.13.2=py310hca03da5_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py310hca03da5_0
  - jellyfish=1.0.1=py310h15d1925_0
  - jinja2=3.1.4=py310hca03da5_0
  - jpeg=9e=h80987f9_3
  - jsonschema=4.19.2=py310hca03da5_0
  - jsonschema-specifications=2023.7.1=py310hca03da5_0
  - jupyter_client=8.6.0=py310hca03da5_0
  - jupyter_core=5.7.2=py310hca03da5_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keyring=24.3.1=py310hca03da5_0
  - kiwisolver=1.4.4=py310h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lazy-object-proxy=1.10.0=py310h80987f9_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialindex=1.9.3=hc377ac9_0
  - libssh2=1.11.0=h3e2b118_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.13.1=h0b34f26_2
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=2.2.0=py310hca03da5_1
  - markupsafe=2.1.3=py310h80987f9_0
  - matplotlib=3.9.2=py310hca03da5_0
  - matplotlib-base=3.9.2=py310h7ef442a_0
  - matplotlib-inline=0.1.6=py310hca03da5_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py310hca03da5_0
  - mistune=2.0.4=py310hca03da5_0
  - more-itertools=10.1.0=py310hca03da5_0
  - multidict=6.7.0=py310h254cc4a_0
  - mypy_extensions=1.0.0=py310hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py310hca03da5_0
  - nbconvert=7.16.6=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbconvert-pandoc=7.16.6=py310hca03da5_0
  - nbformat=5.9.2=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - numpy=1.26.4=py310h3b2db8e_0
  - numpy-base=1.26.4=py310ha9811e2_0
  - numpydoc=1.7.0=py310hca03da5_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=24.1=py310hca03da5_0
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py310hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py310h80987f9_0
  - pip=24.2=py310hca03da5_0
  - platformdirs=3.10.0=py310hca03da5_0
  - pluggy=1.0.0=py310hca03da5_1
  - ply=3.11=py310hca03da5_0
  - prompt-toolkit=3.0.43=py310hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.12.1=py310hca03da5_0
  - pycparser=2.23=py310hca03da5_0
  - pydocstyle=6.3.0=py310hca03da5_0
  - pyflakes=3.2.0=py310hca03da5_0
  - pygithub=2.8.1=py310hca03da5_0
  - pygments=2.15.1=py310hca03da5_1
  - pyjwt=2.10.1=py310hca03da5_0
  - pylint-venv=3.0.3=py310hca03da5_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyobjc-core=10.1=py310h80987f9_0
  - pyobjc-framework-cocoa=10.1=py310hb094c41_0
  - pyobjc-framework-coreservices=10.1=py310hdd8dd1f_0
  - pyobjc-framework-fsevents=10.1=py310hca03da5_0
  - pyparsing=3.1.2=py310hca03da5_0
  - pyqt=5.15.10=py310h313beb8_0
  - pyqt5-sip=12.13.0=py310h80987f9_0
  - pyqtwebengine=5.15.10=py310h313beb8_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.14=hb885b13_1
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-fastjsonschema=2.16.2=py310hca03da5_0
  - python-lsp-black=2.0.0=py310hca03da5_0
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python.app=3=py310h80987f9_1
  - pytoolconfig=1.2.6=py310hca03da5_0
  - pytz=2024.1=py310hca03da5_0
  - pyuca=1.2=py310hca03da5_1
  - pyyaml=6.0.1=py310h80987f9_0
  - pyzmq=25.1.2=py310h313beb8_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py310hca03da5_0
  - qt-main=5.15.2=h0917680_10
  - qt-webengine=5.15.9=h2903aaf_7
  - qtpy=2.4.1=py310hca03da5_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py310hca03da5_0
  - requests=2.32.3=py310hca03da5_0
  - rich=13.7.1=py310hca03da5_0
  - rope=1.12.0=py310hca03da5_0
  - rpds-py=0.10.6=py310hf0e4da2_0
  - rtree=1.0.1=py310hca03da5_0
  - setuptools=72.1.0=py310hca03da5_0
  - sip=6.7.12=py310h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py310hca03da5_0
  - sphinx=7.3.7=py310hca03da5_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.10=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - superqt=0.7.6=py310hd36cdfe_0
  - tabulate=0.9.0=py310hca03da5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py310hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.0.1=py310hca03da5_0
  - tomlkit=0.11.1=py310hca03da5_0
  - tornado=6.4.1=py310h80987f9_0
  - traitlets=5.14.3=py310hca03da5_0
  - typing-extensions=4.11.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - ujson=5.10.0=py310h313beb8_0
  - unicodedata2=15.1.0=py310h80987f9_0
  - unidecode=1.3.8=py310hca03da5_0
  - urllib3=2.2.2=py310hca03da5_0
  - watchdog=4.0.1=py310h80987f9_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310hca03da5_1
  - whatthepatch=1.0.2=py310hca03da5_0
  - wheel=0.43.0=py310hca03da5_0
  - wrapt=1.14.1=py310h1a28f6b_0
  - wurlitzer=3.0.2=py310hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yapf=0.40.2=py310hca03da5_0
  - yarl=1.22.0=py310haa24f5a_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=py310hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - aiohttp==3.13.2
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - async-lru==2.0.5
      - asyncssh==2.21.1
      - bcrypt==5.0.0
      - cattrs==25.3.0
      - cryptography==46.0.3
      - flake8==7.1.2
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==6.31.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-server==2.28.0
      - lsprotocol==2025.0.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandas==2.3.3
      - patsy==1.0.2
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - pylint==3.3.9
      - pynacl==1.6.0
      - python-json-logger==4.0.0
      - python-lsp-ruff==2.3.0
      - python-lsp-server==1.13.1
      - qtawesome==1.4.0
      - qtconsole==5.7.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - ruff==0.14.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - spyder==6.1.0
      - spyder-kernels==3.1.1
      - spyder-notebook==0.7.1
      - statsmodels==0.14.5
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - webcolors==25.10.0
      - websocket-client==1.9.0
prefix: /opt/anaconda3/envs/PSY427_627
