[workspace]
authors = ["Lena-Kemmelmeier <lkemmelmeier@ucsd.edu>"]
channels = ["conda-forge"]
name = "henderson2025"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
render = 'quarto render "writeup/henderson2025_replication_report.qmd" --to html'
preview = 'quarto preview "writeup/henderson2025_replication_report.qmd" --to html'

[dependencies]
quarto = ">=1.8.25,<2"
r-base = ">=4.5.1,<4.6"
r-knitr = ">=1.50,<2"
r-rmarkdown = ">=2.30,<3"
r-tidyverse = ">=2.0.0,<3"
numpy = ">=2.3.4,<3"
pandas = ">=2.3.3,<3"
statsmodels = ">=0.14.5,<0.15"
scipy = ">=1.16.3,<2"
ipykernel = ">=7.1.0,<8"
scikit-learn = ">=1.7.2,<2"
h5py = ">=3.15.1,<4"
matplotlib = ">=3.10.7,<4"
